global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rez-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:5001']
        labels:
          service: 'rez-api'

  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #       labels:
  #         service: 'node-exporter'
